# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 200a7ef521bd251d7c603d5d415b31583b28610a36ac8c5d0899aaacaaf4f79115e239babfb637974b5fdc7fbb01a2157b1a2d5da0cdaed904ed58a8f5ab51fb

test:
  secret_key_base: b740d25e77c2608b98e2ff293527bf1fcb47ee53c5bc68a33c364b411ad167eac8cf3b74fe4fba1d6adb926c33e485f3b751f8469df3e32122a5318e13a9de7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
